### ISSUE TITLE
请教将cebx转为PDF的思路与实现方式

### ISSUE THREAD

**Issue by fandasoft** [weimingtom/cebxconvert#1]
能否告知如何通过代码的方式将cebx转为PDF。谢谢！

**Comment by weimingtom** [comment]
不知道你是不是认识我。我知道一个方法，不过是我朋友想出来的，他是把ceb转换成cebx，然后通过方正的ApaReader.exe的隐藏命令行参数（我就不明说是什么参数了，你应该能猜到），向adobe或者foxit的虚拟打印机打印到pdf文件（虚拟打印机可以设置默认的输出路径和不弹出保存对话框，不过需要先设置一次和打印一次才能生效。虚拟打印机需要设置为默认），每次这个过程之前和之后把相关的进程杀死，需要单队列执行（设置一个轮训超时，如果超时的话也杀死相关的进程）

**Comment by weimingtom** [comment]
如果你有好的方法，欢迎私下告诉我，但你如果是照搬我朋友的方法，麻烦不要到处说

**Comment by weimingtom** [comment]
命令行调用虚拟打印机

**Comment by fandasoft** [comment]
非常感谢您的信息。
我在这方面是个小白， 您说的方法我尝试了一下，有一个问题请教：


我是用/p或者-p的方法来尝试的，不知道是否您所说的参数。 apareader.exe 123.cebx /p , 这个时候会出来两个框，还有一个提示正在打印，还有一个是文件保存地址的框。 打印机已将adobe pdf设置为默认打印机了。 我在打印的默认设置中已经确定了输出路径，但是还是会弹出文件保存的框。我采用类似：apareader.exe 123.cebx /p .\temp\123.pdf 的形式，想指定输出的文件，但不起作用。 不知道这个如何解决，能否请赐教？  非常感谢！



想直接联系您，但是不知道您的邮件地址。 这个邮件好像是github转发的。


Zhenjun
yangzj@fandasoft.com
186 2162 7050




------------------
通过方正的ApaReader.exe的隐藏命令行参数（我就不明说是什么参数了，你应该能猜到），向adobe或者foxit的虚拟打印机打印到pdf文件
-----------------










Best Regards,

杨振军 (Yang Zhen-jun)




Fandasoft.com

yangzj@fandasoft.com




T 86 21 5043 3198

F 86 21 5049 9870

C 86 186 2162 7050









在2019年08月31 19时52分，"weimingtom"<notifications@github.com>写道：

不知道你是不是认识我。我知道一个方法，不过是我朋友想出来的，他是把ceb转换成cebx，然后通过方正的ApaReader.exe的隐藏命令行参数（我就不明说是什么参数了，你应该能猜到），向adobe或者foxit的虚拟打印机打印到pdf文件（虚拟打印机可以设置默认的输出路径和不弹出保存对话框，不过需要先设置一次和打印一次才能生效。虚拟打印机需要设置为默认），每次这个过程之前和之后把相关的进程杀死，需要单队列执行（设置一个轮训超时，如果超时的话也杀死相关的进程）

**Comment by weimingtom** [comment]
关于输出路径问题我也是卡在这里。我试过可以先手工打开apabi阅读器的界面，用它的打印菜单打印一次，然后就可以把pdf输出到默认路径了，你可以试试。我就只知道有斜杠p这个隐藏参数开关可以利用而已，更多就只能靠你自己想了，至于有没有办法通过程序改变输出路径，我没想出来

**Comment by weimingtom** [comment]
因为已经有别人拜托我解决这个问题来赚钱，所以不要再问我了，我怕被别人打死
